name: Deploy Parse Server

on:
  push:
    branches:
      - main

env:
  PARSE_APP_ID: ${{ secrets.PARSE_APP_ID }}
  PARSE_MASTER_KEY: ${{ secrets.PARSE_MASTER_KEY }}
  PARSE_JAVASCRIPT_KEY: ${{ secrets.PARSE_JAVASCRIPT_KEY }}
  PARSE_SERVER_URL: ${{ secrets.PARSE_SERVER_URL }}
  PARSE_PORT_NUMBER: ${{ secrets.PARSE_PORT_NUMBER }}
  PARSE_APP_NAME: ${{ secrets.PARSE_APP_NAME }}
  PARSE_CLOUD_CODE_MAIN: ${{ secrets.PARSE_CLOUD_CODE_MAIN }}
  PARSE_DASHBOARD_USER: ${{ secrets.PARSE_DASHBOARD_USER }}
  PARSE_DASHBOARD_PASS: ${{ secrets.PARSE_DASHBOARD_PASS }}
  SPACES_ENDPOINT: ${{ secrets.SPACES_ENDPOINT }}
  SPACES_BUCKET: ${{ secrets.SPACES_BUCKET }}
  SPACES_BASE_URL: ${{ secrets.SPACES_BASE_URL }}
  SPACES_CDN_BASE_URL: ${{ secrets.SPACES_CDN_BASE_URL }}
  SPACES_REGION: ${{ secrets.SPACES_REGION }}
  SPACES_BUCKET_PREFIX: ${{ secrets.SPACES_BUCKET_PREFIX }}
  SPACES_KEY: ${{ secrets.SPACES_KEY }}
  SPACES_SECRET: ${{ secrets.SPACES_SECRET }}

jobs:
  deploy-parse-server:
    name: Deploy Parse Server
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Ensure target directory exists before uploading files
      - name: Ensure Target Directory Exists
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo mkdir -p /var/www/parse-server
            sudo chown -R $USER:$USER /var/www/parse-server

      # Step 3: Upload Parse Server files
      - name: Upload Parse Server files
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: .
          target: /var/www/parse-server/

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      # Step 4: Install Node.js and PM2 if not present
      - name: Install Node.js and PM2 if not present
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            if ! command -v pm2 &> /dev/null; then
              sudo npm install -g pm2
            fi

      # Step 5: Install project dependencies
      - name: Install Dependencies
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/parse-server
            yarn install

      # Step 6: Start or reload Parse Server using PM2
      - name: Start or Reload Parse Server with PM2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            if pm2 list | grep -q parse-server; then
              pm2 reload parse-server
            else
              pm2 start /var/www/parse-server/index.js --name parse-server
            fi
